### ISSUE TITLE
403 Preload Route denied

### ISSUE THREAD

**Issue by ralonsom** [irontec/itsbc#12]
Some models of phones or PBXs launch the first registration with "Route:".
if the route is Route:domain , sbc answers "403 Preload Route denied". if the route is Route:IP the registry works correctly.

**Comment by cruzccl** [comment]
Hi @ralonsom,

SIP routing defined in RFC 3261 is quite complex, but related to the Record-Route/Route headers, it could be summarized  (and simplified) as:

- Initial request from UAC do not _normally_ contain any of them.

- Traversed proxies may add Record-Route if the want to stay on the signalling path until the end of the dialog.

- Destination UAS must include all the Record-Route in replies so that both UAC and UAS have the same route set for next transations.

- Next in-dialog transaction must add as many Route headers as Record-Routes on the initial route sets, so that messages can be loose routed and traverse all the wanted proxies.

Although UAC behaviour described in [8.1](https://tools.ietf.org/html/rfc3261#section-8.1) even recommends adding a Route in some initial requests, discarding this Routes is considered a good practise to avoid being used as an open relay (read [this](https://lists.kamailio.org/pipermail/sr-users/2012-June/073762.html)). In fact, removing them it is included in [Kamailio's default configuration file](https://github.com/kamailio/kamailio/blob/cf98d1fa997e9b3e818c57d226613a50be0248b1/etc/kamailio.cfg#L488).

But opensips doesn't remove them, it exits (see [here](https://github.com/OpenSIPS/opensips/blob/e1e407fb1dfa2aa272cb4964f482428bde8280d5/etc/opensips.cfg#L169)).

You could try modifying [that logic](https://github.com/irontec/itsbc/blob/9c4e328b256bf60df6464bea0e6bfd1f408543fd/config/opensips/opensips.cfg#L149) and removing Routes instead of exiting (as Kamailio's default config file does).

Regards,
